### ISSUE TITLE
TypeError when running gmvae.py

### ISSUE THREAD

**Issue by drao2** [RuiShu/vae-clustering#1]
Hey there, thanks for the great library - looking forward to getting into GMVAEs!

I've cloned the library and dependencies, but seem to be stuck on this runtime error. I'm on python2.7 so can't see why this shouldn't work out of the box.

Traceback (most recent call last):
File "gmvae.py", line 28, in 
x = Placeholder((None, 784), 'x')
File "build/bdist.macosx-10.10-x86_64/egg/tensorbayes/layers/simple.py", line 10, in placeholder
File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1332, in placeholder
name=name)
File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1748, in _placeholder
name=name)
File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 683, in apply_op
attr_value.type = _MakeType(value, attr_def)
File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 177, in _MakeType
(attr_def.name, repr(v)))
TypeError: Expected DataType for argument 'dtype' not 'x'

**Comment by RuiShu** [comment]
Thanks for checking out the code! One of the dependencies is tensorbayes, which I am still in the process of developing. I haven't gotten round to making sure yet that the changes I made to tensorbayes doesn't break this repo. 

In your particular case, please change
```python
x = Placeholder((None, 784), 'x') -> x = Placeholder((None, 784), name='x')
```

I'll review this repo tonight to make sure things aren't broken.
