### ISSUE TITLE
error for tensorbayes

### ISSUE THREAD

**Issue by wac81** [RuiShu/vae-clustering#4]
Traceback (most recent call last):
  File "/home/wac/PycharmProjects/vae-clustering/gmvae.py", line 3, in <module>
    from tensorbayes.layers import Constant, Placeholder, Dense, GaussianSample
ImportError: cannot import name Constant

tensorbayes == 0.4.0
tensorflow == 1.7.0
how to fix it？

**Comment by RuiShu** [comment]
tensorbayes 0.4.0 isn't backwards compatible with this repo.

Try https://github.com/RuiShu/tensorbayes/releases/tag/0.1.1 
I think that version is compatible.

**Comment by wac81** [comment]
and i get another error：
tensorflow == 1.7.0
tensorflow == 1.1.0  
same error


Traceback (most recent call last):
  File "gmvae_k.py", line 34, in <module>
    x = Placeholder((None, 784), 'x')
  File "/usr/local/lib/python2.7/dist-packages/tensorbayes/layers/simple.py", line 11, in placeholder
    return tf.placeholder(dtype, shape, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1507, in placeholder
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 1997, in _placeholder
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 701, in apply_op
    attr_value.type = _MakeType(value, attr_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 178, in _MakeType
    (attr_def.name, repr(v)))
TypeError: Expected DataType for argument 'dtype' not 'x'.

**Comment by DanielTea** [comment]
I have the same issue, unfortunately tensorbayes is not compatible with python 3.6

**Comment by rxlgq** [comment]
I think you should use the following line
x = Placeholder((None, 784), dtype= 'float32', name = 'x')  to replace the line
x = Placeholder((None, 784), 'x'). 
It will be OK.
